#!/bin/bash
#Runs all tests from specified directory.

if [ "$#" -lt 3 ]; then
  echo "Usage: $0 path-to-binary input-directory output-directory"
  exit 0
fi
mkdir -p $3/$2
find $2 -type f -exec $1 {} $3/{} \;
