#!/bin/bash
if [ "$#" -lt 5 ]; then
  echo "Usage: $0 path-to-binary input-file output-dir from to"
  exit 0
fi
if [ -e .tmpinc ]; then
  rm .tmpinc
fi
mkfifo .tmpinc

echo -e "Seq\t\tTime\t\tRoutes\t\tCost"
for i in `seq $4 $5`; do
  cat $2 | head -n $((9+$i)) > .tmpinc &
  $1 .tmpinc $3/output$i.txt | tail -n +2 | awk -v i=$i '{ printf "%d\t\t%s\n", i, $0 }'
done
